# Generated by Django 2.0.6 on 2018-06-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_adapter', models.CharField(max_length=256)),
                ('host', models.CharField(max_length=64)),
                ('port', models.IntegerField(max_length=10)),
                ('username', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('db_name', models.CharField(max_length=256)),
            ],
        ),
    ]
